server {
    listen 80;
    server_name rdp.samsepiolss.ir;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name rdp.samsepiolss.ir;

    access_log /var/log/nginx/windows/dockur-access.log daas;
    error_log /var/log/nginx/windows/dockur-error.log;

    limit_req zone=general burst=30 nodelay;
    limit_conn addr 100;

    include /etc/nginx/snippets/ssl-params.conf;
    include /etc/nginx/snippets/security-headers.conf;

    location = / {
    return 301 https://$host/rdp/;
    }

    location /rdp/ {
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass http://rdp/guacamole/;
        proxy_cookie_path /guacamole/ /rdp/;
    }

     location /websockify {
        include /etc/nginx/snippets/proxy-params.conf;
        include /etc/nginx/snippets/websocket-upgrade.conf;
        limit_req zone=websocket burst=15 nodelay;
        proxy_pass http://rdp/guacamole;
    }
}

