upstream vnc_windows {
    least_conn;
    keepalive 32;
    server 127.0.0.1:8006 max_fails=3 fail_timeout=30s;
}

upstream rdp {
    least_conn;
    keepalive 32;
    server 127.0.0.1:443 max_fails=3 fail_timeout=30s;
}
